### ISSUE TITLE
feat. 使用 tree 指令代替 dir

### ISSUE THREAD

**Issue by lxl66566** [imvanda/Tree_This_Folder#3]
`tree /f` 的输出看起来可能会更直观
例子:
```
Z:\Temp>tree /f
卷 RamDisk 的文件夹 PATH 列表
卷序列号为 9212-D851
Z:.
│  11fdbdb5-d067-4dc3-ae52-d1e63fd1c1ce.tmp
│  1e4027db-8dac-46e2-ba79-778cc2982fab.tmp
│  38391eb2-0301-44a3-81bd-60ba88c8aadd.tmp
│  sonarsource-cfamily-jni2749246127073893934.dll
│
├─edge_BITS_14096_210521365
├─edge_BITS_14096_585020337
├─hsperfdata
├─msedge_url_fetcher
│      9199e6ec-69d4-41e8-be71-c26029a8e8c1
│
└─vscode-typescript
```

**Comment by imvanda** [comment]
哈哈 项目命名不太准确，是dir，抱歉我的问题😂
有空会加上真 - tree 命令的，感谢指出❤️ 期末考完就搞

**Comment by H1DDENADM1N** [comment]
试试这个 https://github.com/H1DDENADM1N/Tree_This_Folder/releases/tag/v1.3

> `tree /f` 的输出看起来可能会更直观 例子:
> 
> ```
> Z:\Temp>tree /f
> 卷 RamDisk 的文件夹 PATH 列表
> 卷序列号为 9212-D851
> Z:.
> │  11fdbdb5-d067-4dc3-ae52-d1e63fd1c1ce.tmp
> │  1e4027db-8dac-46e2-ba79-778cc2982fab.tmp
> │  38391eb2-0301-44a3-81bd-60ba88c8aadd.tmp
> │  sonarsource-cfamily-jni2749246127073893934.dll
> │
> ├─edge_BITS_14096_210521365
> ├─edge_BITS_14096_585020337
> ├─hsperfdata
> ├─msedge_url_fetcher
> │      9199e6ec-69d4-41e8-be71-c26029a8e8c1
> │
> └─vscode-typescript
> ```
