### ISSUE TITLE
[提议]添加对plantuml的支持

### ISSUE THREAD

**Issue by betasecond** [imvanda/Tree_This_Folder#6]
## 功能描述

PlantUML 是一种流行的工具，用于快速创建 UML 图表。通过将 PlantUML 集成到我们的项目中，我们可以：

- **增强文档质量**：利用 PlantUML，我们可以在文档中包含更清晰、更专业的 UML 图表。
- **提升开发效率**：PlantUML 允许我们快速创建和更新 UML 图，这对于设计和代码审查非常有帮助。
- **改善协作**：通过使用代码来定义图表，我们可以在版本控制中更好地跟踪和审查图表的更改。

## 实施细节

我已经在我的 fork 中实现了这一功能，包括以下改进：

- 添加 复制且输出puml部分
- 添加 复制且输出md或txt或puml部分
## 如何使用
```
# 使用管理员权限打开终端 或 使用sudo
$ cd 复制且输出md或txt或puml
$ .\remove.bat
$ .\add0.bat 
```
右键在目录打开
![image](https://github.com/imvanda/Tree_This_Folder/assets/109186040/f36c89b4-0548-43d1-b3f2-3568b8d6e80d)
已经添加成功,命名是目录名字+内容hash值前六位
```
$ ls | grep puml
d-----          1/1/2024   3:00 PM                ?????md?txt?puml
d-----          1/1/2024   2:45 PM                ?????puml
-a----          1/1/2024   3:00 PM            450 Tree_plantuml_fded21.puml
```
可以将内容复制进
[plantuml](http://www.plantuml.com/)
[draw.io](https://app.diagrams.net/)
[idea 插件](https://plugins.jetbrains.com/plugin/7017-plantuml-integration)
进行查看
以下是一个示例
```
$ tree
Folder PATH listing
Volume serial number is ECB9-5805
C:.
├─assets
├─images
├─inpainter
│  ├─config
│  ├─model
│  │  └─modules
│  └─util
├─templates
├─test_sample
├─tools
└─tracker
    ├─config
    ├─inference
    ├─model
    └─util
```
![image](https://github.com/imvanda/Tree_This_Folder/assets/109186040/ad950a7e-8caa-47bb-9404-52008434136a)

**Comment by imvanda** [comment]
😘感谢代码贡献，之后我再测试学习下，暂时忙考试中...看来大家需求确实各不相同，我在思考如果有需要，后续如何把功能分类，按需安装，因为本意是简单一点......考完再说咯，再次感谢贡献👍

**Comment by H1DDENADM1N** [comment]
我遇到点问题：
tree2puml.exe 探索深度只有一层

**Comment by betasecond** [comment]
> 我遇到点问题： tree2puml.exe 探索深度只有一层

方便提供下复现情况吗,程序本意是与前面的代码一样,以20层为探索深度

**Comment by H1DDENADM1N** [comment]
> > 我遇到点问题： tree2puml.exe 探索深度只有一层
> 
> 方便提供下复现情况吗,程序本意是与前面的代码一样,以20层为探索深度

![图片](https://github.com/imvanda/Tree_This_Folder/assets/65646535/e2d1e7c4-80ff-4747-a0c3-2220b29d329f)

**Comment by H1DDENADM1N** [comment]
> > > 我遇到点问题： tree2puml.exe 探索深度只有一层
> > 
> > 
> > 方便提供下复现情况吗,程序本意是与前面的代码一样,以20层为探索深度
> 
> ![图片](https://private-user-images.githubusercontent.com/65646535/293576020-e2d1e7c4-80ff-4747-a0c3-2220b29d329f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwOTg3NTUsIm5iZiI6MTcwNDA5ODQ1NSwicGF0aCI6Ii82NTY0NjUzNS8yOTM1NzYwMjAtZTJkMWU3YzQtODBmZi00NzQ3LWEwYzMtMjIyMGIyOWQzMjlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAxVDA4NDA1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzYTM4N2E3YjczMWUzNzNlMDI0ZDZhYjE1N2QwOGNjMjMxZjBjOWRiYjZhNmE3NzJlNDQ5MjQxYjk3Y2Q2MzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5w9IPfyNai6EtGXwB0DLqIlD1UF5qunJOiHYR8eRL4A)

如图，再Tree_This_Folder文件夹生成未继续探索。
文件Tree_This_Folder_fded21.puml

@startuml
scale 103500 width
scale 2200 height
package "assets" as assets {
}
package "仅复制" as 仅复制 {
}
package "复制且输出md" as 复制且输出md {
}
package "复制且输出md或txt" as 复制且输出md或txt {
}
package "复制且输出md或txt或puml" as 复制且输出md或txt或puml {
}
package "复制且输出puml" as 复制且输出puml {
}
package "复制且输出txt" as 复制且输出txt {
}
@enduml

**Comment by betasecond** [comment]
> > > 我遇到点问题： tree2puml.exe 探索深度只有一层
> > 
> > 
> > 方便提供下复现情况吗,程序本意是与前面的代码一样,以20层为探索深度
> 
> ![图片](https://private-user-images.githubusercontent.com/65646535/293576020-e2d1e7c4-80ff-4747-a0c3-2220b29d329f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwOTg5MDYsIm5iZiI6MTcwNDA5ODYwNiwicGF0aCI6Ii82NTY0NjUzNS8yOTM1NzYwMjAtZTJkMWU3YzQtODBmZi00NzQ3LWEwYzMtMjIyMGIyOWQzMjlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAxVDA4NDMyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwOTBlMGM1YTQ2YzY2ODllNThjZDI2OTQ5MGUwOWExMmE4YmVmYjg3YTQzZGI0OTJjOTRmN2UxZjczOTZjMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-Fao4RyS28nf1-Yjc41FpOWUctmeyjb0bI30YNaRn9k)

看起来只有一层是符合预期的,因为文件夹里面没有嵌套的文件夹,能提供下当前目录执行tree的信息吗
后续会加入可选的生成 有文件信息 的plantuml图

**Comment by H1DDENADM1N** [comment]
> > > > 我遇到点问题： tree2puml.exe 探索深度只有一层
> > > 
> > > 
> > > 方便提供下复现情况吗,程序本意是与前面的代码一样,以20层为探索深度
> > 
> > 
> > ![图片](https://private-user-images.githubusercontent.com/65646535/293576020-e2d1e7c4-80ff-4747-a0c3-2220b29d329f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwOTg5MDYsIm5iZiI6MTcwNDA5ODYwNiwicGF0aCI6Ii82NTY0NjUzNS8yOTM1NzYwMjAtZTJkMWU3YzQtODBmZi00NzQ3LWEwYzMtMjIyMGIyOWQzMjlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAxVDA4NDMyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwOTBlMGM1YTQ2YzY2ODllNThjZDI2OTQ5MGUwOWExMmE4YmVmYjg3YTQzZGI0OTJjOTRmN2UxZjczOTZjMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-Fao4RyS28nf1-Yjc41FpOWUctmeyjb0bI30YNaRn9k)
> 
> 看起来只有一层是符合预期的,因为文件夹里面没有嵌套的文件夹,能提供下当前目录执行tree的信息吗 后续会加入可选的生成 有文件信息 的plantuml图

哦哦，理解了，只显示文件夹啊

**Comment by H1DDENADM1N** [comment]
> 😘感谢代码贡献，之后我再测试学习下，暂时忙考试中...看来大家需求确实各不相同，我在思考如果有需要，后续如何把功能分类，按需安装，因为本意是简单一点......考完再说咯，再次感谢贡献👍

我提交了新request 添加对plantuml的支持，无冲突
https://github.com/imvanda/Tree_This_Folder/pull/8
